image: python:3.8-bullseye
# This template should be usable on any system that's based on apt.
# taken from tor gitlabci

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SUBDIR: public/manual/
  TRANSLATION_BRANCH: "tbmanual-contentspot"

include:
  - project: tpo/tpa/ci-templates
    file: lektor.yml
